export * from "./services";
export * from "./types";
export * from "./query";
export * from "../providers";
export * from "./dsc-sdk";
export * from "./form-error";
export * from "./ebhulekh";
export * from "./db";
export * from "./dsc.service";
export * from "./dsc-signer";
export * from "./utils";
export * from "./court-dependency";
export * from "./useUserRole";
export * from "./role-utils";
export * from "./case-routing";
export * from "./party-utils";
export * from "./webauthn";
export { apiClient, publicClient } from "./api-client";
export const WEBSITE = process.env.NEXT_PUBLIC_HOME_URL;
export const ACCOUNT = process.env.NEXT_PUBLIC_ACCOUNT_URL;
export const COURT = process.env.NEXT_PUBLIC_COURT_URL;
export const CP = process.env.NEXT_PUBLIC_CP_URL;
export const isDev = process.env.NODE_ENV === "development";
