export const apps = [
  {
    name: "web",
    cwd: "/var/www/rccms/rccms-client",
    script: "node_modules/next/dist/bin/next",
    args: "start -p 3000",
    instances: "max",
    exec_mode: "cluster",
    autorestart: true,
    watch: false,
    max_memory_restart: "700M",
    restart_delay: 3000,
    listen_timeout: 10000,
    kill_timeout: 5000,
    node_args: "--max-old-space-size=630",
    error_file: "./logs/err.log",
    out_file: "./logs/out.log",
    log_date_format: "YYYY-MM-DD HH:mm:ss",
    merge_logs: true,
    time: true,
    env: {
      NODE_ENV: "production",
      PORT: 3000,
    },
  },
];
